#!/usr/bin/env bash
# This script perfroms different action depending on the signal.
echo $$ > /var/run/myscript.pid
my_text="To infinity and beyond"
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit;' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm /var/run/myscript.pid; exit;' SIGQUIT
while true
do
	echo "$my_text"
	sleep 2
done
