#!/usr/bin/env bash
# This script prints th content of a file.
file="/etc/psswd"

if [ -e "$file" ]; then
	while IFS=: read -r username  userid home shell
	do
		echo "$username"
		echo "$userid"
		echo "$home"
	done < "$file"
else
	echo "No such directory"
fi
