#!/usr/bin/env bash
# this script displaysBest School ten times and Hi the 9th time.
i=0
while [ $i -le 10 ]
do
	# echo "Best School"
	if [ $i = 9 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
	((i+=1))
done
